/**
 * @param {string} S
 * @return {string}
 */
var removeDuplicates = function (S) {
  let i = 1;

  while (S.length - 1 >= i) {
    if (S[i] === S[i - 1]) {
      S = S.substring(0, i - 1) + S.substring(i + 1);
      i -= 1;
      continue;
    }

    i += 1;
  }
  return S;
};

var removeDuplicates2 = function (S) {
  let i = 1;
  let result = [S[0]];
  const len = S.length - 1;
  while (i <= len) {
    if (result[result.push(S[i]) - 2] === S[i++]) {
      result.length -= 2;
    }
  }
  return result.join("");
};
console.time("rm");
console.log(
  removeDuplicates2(
    "abbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbacaabbaca",
  ),
);
console.timeEnd("rm");
